### ISSUE TITLE
1.03 fails to build: error: "Unsupported platform"

### ISSUE THREAD

**Issue by yurivict** [werman/noise-suppression-for-voice#147] opened 2022-09-25 06:15 UTC
```
In file included from /disk-samsung/freebsd-ports/audio/noise-suppression-for-voice-lv2/work/noise-suppression-for-voice-1.03/external/JUCE/modules/juce_audio_plugin_client/LV2/juce_LV2_Client.cpp:48:
In file included from /disk-samsung/freebsd-ports/audio/noise-suppression-for-voice-lv2/work/noise-suppression-for-voice-1.03/external/JUCE/modules/juce_audio_processors/format_types/juce_LV2Common.h:30:
/disk-samsung/freebsd-ports/audio/noise-suppression-for-voice-lv2/work/noise-suppression-for-voice-1.03/external/JUCE/modules/juce_audio_processors/format_types/LV2_SDK/juce_lv2_config.h:76:4: error: "Unsupported platform"
  #error "Unsupported platform"
   ^
In file included from /disk-samsung/freebsd-ports/audio/noise-suppression-for-voice-lv2/work/noise-suppression-for-voice-1.03/external/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp:26:
/disk-samsung/freebsd-ports/audio/noise-suppression-for-voice-lv2/work/noise-suppression-for-voice-1.03/external/JUCE/modules/juce_audio_plugin_client/LV2/juce_LV2_Client.cpp:854:14: error: "LV2 UI is unsupported on this platform"
            #error "LV2 UI is unsupported on this platform"
             ^
/disk-samsung/freebsd-ports/audio/noise-suppression-for-voice-lv2/work/noise-suppression-for-voice-1.03/external/JUCE/modules/juce_audio_plugin_client/LV2/juce_LV2_Client.cpp:859:28: error: expected ';' after expression
                  "\ta ui:" JUCE_LV2_UI_KIND " ;\n"
                           ^
                           ;
/disk-samsung/freebsd-ports/audio/noise-suppression-for-voice-lv2/work/noise-suppression-for-voice-1.03/external/JUCE/modules/juce_audio_plugin_client/LV2/juce_LV2_Client.cpp:859:29: error: use of undeclared identifier 'JUCE_LV2_UI_KIND'
                  "\ta ui:" JUCE_LV2_UI_KIND " ;\n"
                            ^
```

Bundled JUCE breaks. We have the JUCE package.

Please allow to use external JUCE package.

FreeBSD 13.1

**Comment by werman** [comment] 2022-10-16 12:54
Duplicate of https://github.com/werman/noise-suppression-for-voice/issues/131

**Closed** 2023-01-24 11:33 UTC
